"""001-Init

Revision ID: ad4983d5d6ad
Revises:
Create Date: 2024-05-03 19:19:57.369116

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'ad4983d5d6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('type', src.modules.core.models.event_log.SAEventType(), nullable=False),
    sa.Column('event', src.modules.core.models.event_log.SAEvent(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_object_id'), 'events_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_events_log_type'), 'events_log', ['type'], unique=False)
    op.create_index(op.f('ix_events_log_user_id'), 'events_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_log_user_id'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_type'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_object_id'), table_name='events_log')
    op.drop_table('events_log')
    # ### end Alembic commands ###
